Rise-Vision/rise-player

.gitignore
README.md
circle.yml
pom.xml
src/main/java/com/risevision/riseplayer/Config.java
src/main/java/com/risevision/riseplayer/DisplayError.java
src/main/java/com/risevision/riseplayer/DisplayErrors.java
src/main/java/com/risevision/riseplayer/Globals.java
src/main/java/com/risevision/riseplayer/Log.java
src/main/java/com/risevision/riseplayer/Main.java
src/main/java/com/risevision/riseplayer/server/HttpConstants.java
src/main/java/com/risevision/riseplayer/server/HttpUtils.java
src/main/java/com/risevision/riseplayer/server/WebServer.java
src/main/java/com/risevision/riseplayer/server/Worker.java
src/main/java/com/risevision/riseplayer/timers/DisplayErrorsTimer.java
src/main/java/com/risevision/riseplayer/timers/HeartbeatTimer.java
src/main/java/com/risevision/riseplayer/timers/RestartTimer.java
src/main/java/com/risevision/riseplayer/utils/SystemInfo.java
src/main/java/com/risevision/riseplayer/utils/Utils.java
src/main/java/com/risevision/riseplayer/utils/WindowUtils.java

Basic CI infrastructure ready, pending deployment action (copy jar file to remote server)
@tejohnso please review

Initial project setup

---

pom.xml

This adds the required Manifest file to provide a default endpoint on the generated artifact.
@tejohnso please review

Create manifest for artifact

---

src/main/java/com/risevision/riseplayer/utils/Utils.java

Disable Chrome's first run checks

---

src/main/java/com/risevision/riseplayer/utils/UpdateUtils.java
src/main/java/com/risevision/riseplayer/utils/Utils.java

Use install-versions.risevision.com for components' versions check

---

src/main/java/com/risevision/riseplayer/utils/UpdateUtils.java

Avoid restarting player for updates if stable or latest channel match local versions. In case forceStable is used, only check stable channel
@tejohnso please review

Staged rollouts

---

src/main/java/com/risevision/riseplayer/utils/Utils.java

Enable touch events on Linux player

---

src/main/java/com/risevision/riseplayer/utils/Utils.java

Avoid loading Adobe's Flash library and use libpepper instead

---

src/main/java/com/risevision/riseplayer/DisplayErrors.java
src/main/java/com/risevision/riseplayer/Main.java

Remove root checks on Linux

---

src/main/java/com/risevision/riseplayer/utils/Utils.java

Add touch device id detection

---

src/main/java/com/risevision/riseplayer/utils/SystemInfo.java

Provide local IP to Viewer

---

src/main/java/com/risevision/riseplayer/DisplayErrors.java
src/main/java/com/risevision/riseplayer/Globals.java
src/main/java/com/risevision/riseplayer/Main.java
src/main/java/com/risevision/riseplayer/externallogger/ExternalLogger.java
src/main/java/com/risevision/riseplayer/externallogger/InsertSchema.java
src/main/java/com/risevision/riseplayer/server/WebServer.java
src/main/java/com/risevision/riseplayer/server/Worker.java
src/main/java/com/risevision/riseplayer/timers/HeartbeatTimer.java
src/main/java/com/risevision/riseplayer/timers/RestartTimer.java
src/main/java/com/risevision/riseplayer/utils/UpdateUtils.java
src/main/java/com/risevision/riseplayer/utils/Utils.java

Improve BQ logging

---

src/main/java/com/risevision/riseplayer/Config.java
src/main/java/com/risevision/riseplayer/timers/RestartTimer.java

Add restartoverride=true to RiseDisplayNetwork.ini

Enable scheduled restart override

---

LICENSE.md

Add GPLv3 license

---

src/main/java/com/risevision/riseplayer/Config.java
src/main/java/com/risevision/riseplayer/utils/Utils.java

Load browser arguments configuration from .ini file

---

src/main/java/com/risevision/riseplayer/Config.java

Add Chrome command line arguments to hide "Restore" popup

---

.gitignore
src/main/java/com/risevision/riseplayer/Config.java
src/main/java/com/risevision/riseplayer/DisplayError.java
src/main/java/com/risevision/riseplayer/DisplayErrors.java
src/main/java/com/risevision/riseplayer/Globals.java
src/main/java/com/risevision/riseplayer/Log.java
src/main/java/com/risevision/riseplayer/Main.java
src/main/java/com/risevision/riseplayer/externallogger/ExternalLogger.java
src/main/java/com/risevision/riseplayer/externallogger/InsertSchema.java
src/main/java/com/risevision/riseplayer/externallogger/Token.java
src/main/java/com/risevision/riseplayer/server/HttpConstants.java
src/main/java/com/risevision/riseplayer/server/HttpUtils.java
src/main/java/com/risevision/riseplayer/server/WebServer.java
src/main/java/com/risevision/riseplayer/server/Worker.java
src/main/java/com/risevision/riseplayer/timers/DisplayErrorsTimer.java
src/main/java/com/risevision/riseplayer/timers/HeartbeatTimer.java
src/main/java/com/risevision/riseplayer/timers/RestartTimer.java
src/main/java/com/risevision/riseplayer/utils/SystemInfo.java
src/main/java/com/risevision/riseplayer/utils/UpdateUtils.java
src/main/java/com/risevision/riseplayer/utils/Utils.java
src/main/java/com/risevision/riseplayer/utils/WindowUtils.java

Assumptions:
- this program eventually becomes rvplayer

Add tracking for successful restarts.

---

src/main/java/com/risevision/riseplayer/Config.java
src/main/java/com/risevision/riseplayer/Main.java
src/main/java/com/risevision/riseplayer/timers/RestartTimer.java
src/main/java/com/risevision/riseplayer/utils/Utils.java

Also change method names from "restarting player" to plain "restarting"

Fix restart tracking

---

src/main/java/com/risevision/riseplayer/Config.java

@fjvallarino @tejohnso 
Previous comments in #29
- pass a parameter to Chrome that disables scrolling through history
- this should fix Rise-Vision/viewer#80

Fix history gesture issue

---

src/main/java/com/risevision/riseplayer/Globals.java

@fjvallarino @ahmedalsudani Please review.  We can overwrite the existing player zip and tar.gz files with the same file name to deploy.

Set correct player version

---

src/main/java/com/risevision/riseplayer/server/Worker.java
src/main/java/com/risevision/riseplayer/utils/Utils.java

@tejohnso @ahmedalsudani please review

Fix reboot issue

---

src/main/java/com/risevision/riseplayer/Config.java
src/main/java/com/risevision/riseplayer/Main.java
src/main/java/com/risevision/riseplayer/utils/Utils.java

@fjvallarino @tejohnso please review.
Functionality till needs to be tested on Windows.

Log graceful shutdowns

---

src/main/java/com/risevision/riseplayer/Main.java

@ahmedalsudani @fjvallarino please review

Shutdown any existing browser before starting

---

src/main/java/com/risevision/riseplayer/utils/Utils.java

@fjvallarino @ahmedalsudani  please review.

Don't invoke the installer directly - use scripts

---

src/main/java/com/risevision/riseplayer/Globals.java

@ahmedalsudani @fjvallarino I've updated the bucket components dir with this version of the player.

Update player version

---

src/main/java/com/risevision/riseplayer/utils/Utils.java

@ahmedalsudani @fjvallarino please review.

Launch installer restart as a separate process

---

src/main/java/com/risevision/riseplayer/Config.java
src/main/java/com/risevision/riseplayer/utils/SystemInfo.java
src/main/java/com/risevision/riseplayer/utils/Utils.java

@tejohnso @ahmedalsudani please review

Use version directory, if available, only for Chrome and .ver related operations; othewise, use base rvplayer directory

---

src/main/java/com/risevision/riseplayer/utils/Utils.java

Change launcher call to handle usernames with spaces

---

src/main/java/com/risevision/riseplayer/utils/Utils.java

Add cmd /c back into the exec command

---

src/main/java/com/risevision/riseplayer/Config.java
src/main/java/com/risevision/riseplayer/Globals.java
src/main/java/com/risevision/riseplayer/Main.java
src/main/java/com/risevision/riseplayer/server/Worker.java
src/main/java/com/risevision/riseplayer/utils/Utils.java

@tejohnso @ahmedalsudani please review

Integrate electron browser

---

src/main/java/com/risevision/riseplayer/timers/RestartTimer.java

@tejohnso @ahmedalsudani please review

Set graceful shutdown flag on scheduled restarts

---

src/main/java/com/risevision/riseplayer/server/Worker.java
src/main/java/com/risevision/riseplayer/timers/RestartTimer.java
src/main/java/com/risevision/riseplayer/utils/Utils.java

@fjvallarino @tejohnso ready for review

Treat user-initiated actions as graceful
